[project]
name = "platform-app"
version = "0.1.0"
description = "This is a samlpe project to learn devops deployments"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.127.0",
    "uvicorn>=0.40.0",
]
